### ISSUE TITLE
knife ec backup fails if --concurrency set to 20

### ISSUE THREAD

**Issue by OBrienCommaJosh** [chef/knife-ec-backup#136]
# Version:

knife-ec-backup 2.4.6

# Environment:

```
         Product: Chef-Server 13.1.13
      AWS Native: No
       CPU Cores: 4
       CPU Model: Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz
    Total Memory: 5805 MB
     Free Memory: 3939 MB
        Platform: CentOS Linux release 7.3.1611 (Core)
          Uptime: 18:50:24 up 35 days,  8:32,  2 users,  load average: 0.16, 0.11, 0.08
       Reporting: 1.8.0
          Manage: 2.5.16
Push-Jobs Server: Not Installed
    LDAP Enabled: No
    DRBD Enabled: No
    HA Front-End: Yes
```

# Scenario:

With knife ec backup version 2.4.6 and chef server version 13.1.13, when the user runs `knife ec backup` with `--concurrency 20`, they get a segmentation fault. We suspect a ruby version upgrade may be at fault.

# Steps to Reproduce:

Run `knife ec backup --concurrency 20` against a chef server with a large dataset (i.e. over 1000 orgs)

# Expected Result:

`knife ec backup --concurrency` succeeds and fails predictably based on the available resources, and failure messages are helpful to the user.

# Actual Result:

```
/opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:258: [BUG] Segmentation fault at 0x0000000000ebd688
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
```

**Comment by OBrienCommaJosh** [comment]
Customer Bugs Issue: https://github.com/chef/customer-bugs/issues/71

**Comment by snehaldwivedi** [comment]
@lamont-granquist I have tested `knife ec backup --concurrency 20`  with knife ec backup version 2.4.6 and chef server version 13.1.13 as mention against a chef server with across over 1013 organisations and have replicated any issue.

**Comment by dheerajd-msys** [comment]
Thanks @snehaldwivedi to confirm this, customer case is closed related to this issue. They will come up with a new issue if they confront this again.
