### ISSUE TITLE
knife ec backup stopped working with Chef Workstation version: 21.8.555

### ISSUE THREAD

**Issue by amousa1968** [chef/knife-ec-backup#161]
# Version:

Chef Workstation version: 21.8.555

# Environment:

Linux

# Scenario:

[mousaa@p1l00564g chef-repo]$ knife ec backup $backup --webui-key $pemfiles/p1l00560g.webui_priv_src.pem --profile hpe_colo_1^C
[mousaa@p1l00564g chef-repo]$ knife ec backup $backup
FATAL: Cannot find subcommand for: 'ec backup'
Available subcommands: (for details, knife SUB-COMMAND --help)

Was knife ec backup deprecated in the new chef workstation release?

**Comment by amousa1968** [comment]
Did knife ec backup change to knife download and upload?

**Comment by tas50** [comment]
The fix for this issue has been merged into our main branch and will ship shortly
