### ISSUE TITLE
backup with --purge does not cleanup ACLs for clients and nodes

### ISSUE THREAD

**Issue by collinmcneese** [chef/knife-ec-backup#162]
# Version:

- `2.4.15`

# Environment:

- Chef Infra Server `14.9.23`
- Chef Infra Server (Automate Deployed) `14.4.4`

# Scenario:

As a customer with multiple data-center locations, part of the DR strategy is to use `knife ec backup` and `knife ec restore` to keep the recovery site up-to-date with data from the primary site.  

When running `knife ec backup` with the `purge` option, if nodes and/or clients are deleted between backup runs the `client` and `node` objects are removed from the backup directory on the next run, but associated ACLs are not.  This causes issues with restore of the backup to a target system with orphaned `acl` objects that have no associated `client` or `node`

# Steps to Reproduce:

- Take an initial backup using `knife ec backup`
```plain
/opt/opscode/embedded/bin/knife ec backup /backup --sql-db automate-cs-oc-erchef  --purge -V -s https://FQDN
```
- Delete a `node` and/or `client` from the Chef Infra Server
```plain
$ knife node delete -y client03
Deleted node[client03]
$ knife client delete -y client03
Deleted client[client03]
```
- Run `knife ec backup` again with the `--purge` option
```plain
/opt/opscode/embedded/bin/knife ec backup /backup --sql-db automate-cs-oc-erchef  --purge -V -s https://FQDN
```

# Expected Result:

knife-ec-backup should remove the node/client objects and their associated ACLs during the purge process since all objects have been removed from the server using standard `knife node delete` or `knife client delete` commands

# Actual Result:

knife-ec-backup will purge (remove) the local copies of the node and client JSON files, but it will not remove their associated acl JSON files, even though the server no longer has the objects.

Output from a knife-ec-backup run with `purge` enabled where `client` and `node` objects are deleted:

```plain
[root@ip-172-22-1-219 ~]# find /backup/ -name 'client03.json'
/backup/organizations/cslocal/acls/clients/client03.json
/backup/organizations/cslocal/acls/nodes/client03.json
/backup/organizations/cslocal/clients/client03.json
/backup/organizations/cslocal/nodes/client03.json

[root@ip-172-22-1-219 ~]# /opt/opscode/embedded/bin/knife ec backup /backup --sql-db automate-cs-oc-erchef  --purge -V -s https://FQDN
WARNING: No knife configuration file found. See https://docs.chef.io/config_rb/ for details.
Downloading Users
Downloading organization object for cslocal from https://FQDN/organizations/cslocal
Copying /acls/groups/billing-admins.json
Copying /groups/billing-admins.json
Copying /groups/admins.json
Copying /acls/groups/public_key_read_access.json
Copying /groups/public_key_read_access.json
Copying /clients
Deleted extra entry /clients/client03.json (purge is on)
... truncated ...
Deleted extra entry /nodes/client03.json (purge is on)
... truncated ...
Updated /groups/clients.json
Copying /groups/users.json
** Finished **
```

The associated ACL files for the deleted client03 `node` and `client` are still present after this run and follow-up runs as well:

```plain
find /backup/ -name 'client03.json'
/backup/organizations/cslocal/acls/clients/client03.json
/backup/organizations/cslocal/acls/nodes/client03.json
```

**Comment by lbakerchef** [comment]
@collinmcneese This is an example of a fantastically-written issue with (seemingly - I'm just starting to have a look) much of the context needed for a developer to begin understanding the issue.

**Comment by PrajaktaPurohit** [comment]
https://github.com/chef/knife-ec-backup/pull/171
