### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by bmhatfield** [chef/knife-ec-backup#85]
Hi there,

I decided to file this as an issue rather than bumping the version to start.

[This issue](https://github.com/chef/knife-ec-backup/pull/80), already fixed, is no fun for me on my Chef Server. It'd be sweet if a new version could be cut, since 2.0.6 appears to be from July 2015.

Thoughts?

**Comment by stevendanna** [comment]
Hi, apologies nobody responded to this.  Since a few versions have been cut since 2.0.6 at this point so I'm going to close this ticket.
